logback:
    configurationFile: classpath:logback-spring.xml
logging:
    file: mts-bridge.log
    file.path: logs/
    level:
        root: INFO
    pattern:
        console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
        file: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
server:
    port: 7788
spring:
mqtt:
    broker.url: 'tcp://5.189.134.159:1883'
    topic: 'application/mts'
